function [nextState, storage] = euler_f_step(...
    dt,...
    currentTime,...
    currentState,...
    currentInput,...
    f,...
    storage...
    )
[currentdState, storage] = f(currentTime, currentState, currentInput, storage);
nextState = currentState + currentdState * dt;
end