function [nextState, currentdState, storage] = euler_f_step(...
    numStates,...
    numInputs,...
    dt,...
    currentTime,...
    currentState,...
    currentInput,...
    f,...
    storage...
    )
[currentdState, storage] = f(numStates, numInputs, currentTime, currentState, currentInput, storage);
nextState = currentState + currentdState * dt;
end