function [b] = firstOrderLag(tau)
    numBlocks = numel(tau);
    assert(numBlocks > 0);
	b = struct;
	b.numInputs = numBlocks;
	b.numOutputs = numBlocks;
	b.numStates = numBlocks;
	b.storage = tau;
	b.f = @physics;
	b.h = @output;
end

function [dState, storage] = physics(...
	numStates,...
	numInputs,...
	time,...
	state,...
	input,...
	tau...
)
	dState = (input - state) ./ tau;
end

function [output, storage] = output(...
	numStates,...
	numOutputs,...
	time,...
	state,...
	tau...
)
    output = state;
end

