function [b] = integrator(numBlocks)
	assert(numBlocks > 0);
    b = struct;
	b.numStates = numBlocks;
	b.numInputs = numBlocks;
	b.numOutputs = numBlocks;
	b.storage = [];
	b.f = @physics;
	b.h = @output;
end

function [dState, storage] = physics(...
	numStates,...
	numInputs,...
	time,...
	state,...
	input,...
	storage...
)
dState = input;
end

function [output, storage] = output(...
	numStates,...
	numOutputs,...
	time,...
	state,...
	storage...
)
output = state;
end

