function [nextState, A, storage] = rk4_f_step(...
    numStates,...
    numInputs,...
    dt,...
    currentTime,...
    currentState,...
    currentInput,...
    currentInput2,...
    nextInput,...
    f,...
    storage...
    )
dt2 = dt / 2;
currentTime2 = currentTime + dt2;
nextTime = currentTime + dt;
[A, storage] = f(numStates, numInputs, currentTime, currentState, currentInput, storage);
nextState = currentState + A * dt2;

[B, storage] = f(numStates, numInputs, currentTime2, nextState, currentInput2, storage);
nextState = currentState + B * dt2;

[C, storage] = f(numStates, numInputs, currentTime2, nextState, currentInput2, storage);
nextState = currentState + C * dt;

[D, storage] = f(numStates, numInputs, nextTime, nextState, nextInput, storage);
nextState = currentState + dt * (A + 2 * B + 2 * C + D) / 6;
end